### ISSUE TITLE
Tree view contents overlap folder name

### ISSUE THREAD

**Issue by mrmurphy** [jmcalaway/atom-alphabet-ui#2]
Hi! Thanks for making this super neat theme.

I noticed when I popped open the sidebar, and scrolled down, that the folder contents overlap the name of the folder:

<img width="225" alt="screenshot 2016-07-19 10 30 33" src="https://cloud.githubusercontent.com/assets/1227109/16958014/0a039b4e-4d9c-11e6-9f2c-36f4aa2f5e1f.png">

Again, thanks!

**Comment by jeffcalaway** [comment]
Hey @splodingsocks thanks for downloading the Climate theme! I'd love to help you get this figured out right away!

I have the theme open but I'm not getting the same results. Can you double-check your Atom's stylesheet to make sure there isn't any residual css that might be interrupting the theme? Would you also mind taking a few screenshots of the following:

-- The whole window
-- Your theme settings

Thank you!

**Comment by mrmurphy** [comment]
Thanks for the quick response! I've disabled all of my custom styles, and I'm still getting the behavior.

Here's a screenshot of the window & settings:

![screenshot 2016-07-19 10 37 32](https://cloud.githubusercontent.com/assets/1227109/16958287/1a4c2ef2-4d9d-11e6-8f48-5c70b1501943.png)

I am running a custom build of Atom, which could be contributing to the situation, but I won't be able to try the normal build for a while, sorry!

**Comment by jeffcalaway** [comment]
Okay! Looking into it. Meanwhile, can you go to View->Developer->Window Reload and see if the issue remains? Sometimes Atom has issues when switching themes.

**Comment by mrmurphy** [comment]
Aha! That's got it fixed. I even thought of that, but I didn't do it. Thanks!

**Comment by jeffcalaway** [comment]
Great! Enjoy!
