### ISSUE TITLE
Open files are dimmed regardless settings

### ISSUE THREAD

**Issue by wdanilo** [jmcalaway/atom-alphabet-ui#7]
Hi!
In the newest atom the opened files are dimmed in disraction free mode even if we set them to be shown. Is this a known bug and do you plan any solution for it? :)

**Comment by jeffcalaway** [comment]
Hello wdanilo,

Unfortunately, with the release of the newest version of Atom, there are a number of known issues with this theme that I don't currently have the time to address. I will accept any pull requests though!

I'm so sorry for the inconvenience!

**Comment by jeffshaver** [comment]
@jmcalaway it seems as though `treeViewPkg.mainModule.createView();` isn't a thing anymore. It seems to work if this line is changed to `treeViewPkg.mainModule.treeView;`, but am unsure if this is the right way to do it. if it is fine, i could put in a pr. Also, the event listener that gets added a bit further down can be removed.
